version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
